"""
Internal core namespace of Rela2x.

This module centralises the re-export of the internal core functionality of
Rela2x. In normal use, the public package namespace should be preferred::

    from rela2x import *

Direct imports from :mod:`rela2x._core` remain possible, but they are intended
primarily for internal use, testing, and advanced development workflows.
"""

from ._settings import set_relaxation_theory
from ._constants import (
    hbar,
    k_B,
    mu_0,
    y_0,
    w_0,
    B,
    T,
    beta,
    t,
    tau,
    tau_c,
)
from ._nmr_isotopes import (
    ISOTOPES,
    spin_quantum_numbers,
)
from ._la import (
    Kronecker_product,
    commutator,
    Lv_bracket,
    Lv_norm,
    Lv_amplitude,
    op_change_of_basis,
    op_decomposition,
)
from ._utils import (
    string_to_number,
    sort_interactions,
    pick_from_list,
    pick_from_matrix,
    cut_list,
    cut_matrix,
    list_indexes,
    all_combinations,
)
from ._symbols import (
    op_S_symbol,
    product_op_S_symbol,
    op_T_symbol,
    product_op_T_symbol,
    expectation_value,
    f_expectation_value_t,
)
from ._operators import (
    op_Sx,
    op_Sy,
    op_Sz,
    op_Sp,
    op_Sm,
    op_Svec,
    vector_to_spherical_tensor,
    op_T,
    op_T_coupled_lq,
    many_spin_operator,
    SpinOperators,
)
from ._superoperators import (
    vectorize,
    vectorize_all,
    sop_rmul,
    sop_lmul,
    sop_commutator,
    sop_double_commutator,
    sop_D,
)
from ._basis import (
    T_index_spin_order,
    T_index_coherence_order,
    T_index_type,
    T_index_spin_projection,
    T_index_from_string,
    S_index_from_string,
    basis_index_list_index,
    coherence_order_filter,
    spin_order_filter,
    type_filter,
    Cartesian_product_basis,
    Cartesian_product_basis_symbols,
    Cartesian_product_basis_and_symbols,
    T_product_basis,
    T_product_basis_symbols,
    Cartesian_product_basis_indices,
    T_product_basis_indices,
    T_index_coherence_sort_key,
    T_index_projection_sort_key,
    T_basis_sort_keys,
    sort_T_product_basis,
    T_product_basis_and_symbols,
)
from ._operator_classes import (
    Operator,
    Superoperator,
)
from ._visualization import (
    matrix_nonzeros,
    visualize_operator,
    visualize_many_operators,
)
from ._spectral_density import (
    Lorentzian,
    Schofield_theta,
    J_w,
    J_w_isotropic_rotational_diffusion,
    extract_J_w_symbols_and_args,
)
from ._relaxation import (
    sop_R_term,
    sop_R_term_alpha_alpha,
    sop_R_term_alpha_beta,
    sop_R_term_beta_alpha,
    sop_R_term_beta_beta,
    sop_R,
)
from ._relaxation_superoperator import RelaxationSuperoperator
from ._master_equations import (
    equations_of_motion,
    equations_of_motion_to_latex,
)
from ._workflows import R_object_in_product_operator_basis

# Explicit internal interface, mirroring the public package namespace.
__all__ = [
    "set_relaxation_theory",
    "hbar",
    "k_B",
    "mu_0",
    "y_0",
    "w_0",
    "B",
    "T",
    "beta",
    "t",
    "tau",
    "tau_c",
    "ISOTOPES",
    "spin_quantum_numbers",
    "Kronecker_product",
    "commutator",
    "Lv_bracket",
    "Lv_norm",
    "Lv_amplitude",
    "op_change_of_basis",
    "op_decomposition",
    "string_to_number",
    "sort_interactions",
    "pick_from_list",
    "pick_from_matrix",
    "cut_list",
    "cut_matrix",
    "list_indexes",
    "all_combinations",
    "op_S_symbol",
    "product_op_S_symbol",
    "op_T_symbol",
    "product_op_T_symbol",
    "expectation_value",
    "f_expectation_value_t",
    "op_Sx",
    "op_Sy",
    "op_Sz",
    "op_Sp",
    "op_Sm",
    "op_Svec",
    "vector_to_spherical_tensor",
    "op_T",
    "op_T_coupled_lq",
    "many_spin_operator",
    "SpinOperators",
    "vectorize",
    "vectorize_all",
    "sop_rmul",
    "sop_lmul",
    "sop_commutator",
    "sop_double_commutator",
    "sop_D",
    "T_index_spin_order",
    "T_index_coherence_order",
    "T_index_type",
    "T_index_spin_projection",
    "T_index_from_string",
    "S_index_from_string",
    "basis_index_list_index",
    "coherence_order_filter",
    "spin_order_filter",
    "type_filter",
    "Cartesian_product_basis",
    "Cartesian_product_basis_symbols",
    "Cartesian_product_basis_and_symbols",
    "T_product_basis",
    "T_product_basis_symbols",
    "Cartesian_product_basis_indices",
    "T_product_basis_indices",
    "T_index_coherence_sort_key",
    "T_index_projection_sort_key",
    "T_basis_sort_keys",
    "sort_T_product_basis",
    "T_product_basis_and_symbols",
    "Operator",
    "Superoperator",
    "matrix_nonzeros",
    "visualize_operator",
    "visualize_many_operators",
    "Lorentzian",
    "Schofield_theta",
    "J_w",
    "J_w_isotropic_rotational_diffusion",
    "extract_J_w_symbols_and_args",
    "sop_R_term",
    "sop_R_term_alpha_alpha",
    "sop_R_term_alpha_beta",
    "sop_R_term_beta_alpha",
    "sop_R_term_beta_beta",
    "sop_R",
    "RelaxationSuperoperator",
    "equations_of_motion",
    "equations_of_motion_to_latex",
    "R_object_in_product_operator_basis",
]
